CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL UNIQUE ,
    email      VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255),
    created_at TIMESTAMP(6)
);

CREATE TABLE incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    severity VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    reported_by_id BIGINT NOT NULL,
    closed_by_id BIGINT
);

ALTER TABLE incidents ADD CONSTRAINT fk_incident_reporter FOREIGN KEY (reported_by_id) REFERENCES users(id);