CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE incident_tags (
    incident_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (incident_id, tag_id),
    CONSTRAINT fk_incident_tags_incident
                           FOREIGN KEY (incident_id)
                           REFERENCES incidents (id),
    CONSTRAINT fk_incident_tags_tag
                           FOREIGN KEY (tag_id)
                           REFERENCES tags (id)
)