CREATE TABLE revinfo
(
    rev      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT,
    user_id  BIGINT
);

CREATE TABLE incidents_aud
(
    id             BIGINT  NOT NULL,
    rev            INTEGER NOT NULL,
    revtype        SMALLINT,
    description    VARCHAR(255),
    severity       VARCHAR(50),
    status         VARCHAR(50),
    created_at     TIMESTAMP(6),
    deleted        BOOLEAN,
    reported_by_id BIGINT,
    closed_by_id   BIGINT,
    updated_at     TIMESTAMP(6),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_incidents_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);


CREATE TABLE users_aud
(
    id         BIGINT  NOT NULL,
    rev        INTEGER NOT NULL,
    revtype    SMALLINT,
    username   VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    created_at TIMESTAMP(6),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_users_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE tags_aud
(
    id      BIGINT  NOT NULL,
    rev     INTEGER NOT NULL,
    revtype SMALLINT,
    name    VARCHAR(255),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_tags_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE incident_tags_aud
(
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    incident_id BIGINT  NOT NULL,
    tag_id      BIGINT  NOT NULL,
    PRIMARY KEY (rev, incident_id, tag_id),
    CONSTRAINT fk_incident_tags_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);